#!/usr/bin/sh

set -eux

SOCAT="$1"
SERVER="$2"

# Meet DBus bus and path name constraints
TEST_NAME="$(basename "$0" | tr '-' '_')"_${$}
TEST_DIR="$(mktemp --tmpdir --directory "${TEST_NAME}.XXXXXX")"
SOCAT_PID=""
SERVER_PID=""

cd "$TEST_DIR"

cleanup()
{
  if [ -n "$SOCAT_PID2" ] && kill -0 "$SOCAT_PID2" 2>/dev/null; then
    kill "$SOCAT_PID2"
  fi
  if [ -n "$SERVER_PID" ] && kill -0 "$SERVER_PID" 2>/dev/null; then
    kill "$SERVER_PID"
  fi
  if [ -n "$SOCAT_PID" ] && kill -0 "$SOCAT_PID" 2>/dev/null; then
    kill "$SOCAT_PID"
  fi
  wait
  cd -
  rm -rf "$TEST_DIR"
}

trap cleanup EXIT

TEST_CONF="${TEST_NAME}.conf"
TEST_LOG="${TEST_NAME}.log"

TEST_NAME_OTHER="${TEST_NAME}_other"
TEST_LOG_OTHER="${TEST_NAME_OTHER}.log"

cat <<EOF > "$TEST_CONF"
active-console = $TEST_NAME
[$TEST_NAME]
logfile = $TEST_LOG
console-id = $TEST_NAME
[$TEST_NAME_OTHER]
logfile = $TEST_LOG_OTHER
console-id = $TEST_NAME_OTHER
EOF

"$SOCAT" -u PTY,raw,echo=0,link=remote PTY,raw,echo=0,wait-slave,link=local &
SOCAT_PID="$!"
while ! [ -e remote -a -e local ]; do sleep 1; done

"$SERVER" --config "$TEST_CONF" "$(realpath local)" &
SERVER_PID="$!"

while ! busctl status --user xyz.openbmc_project.Console."${TEST_NAME}"; do sleep 1; done

echo "log-for-console-1" > remote
sleep 1
grep -qF "log-for-console-1" "$TEST_LOG"

# change the active console
socat -u "ABSTRACT:obmc-console.${TEST_NAME_OTHER}" CREATE:socket_read.txt &
SOCAT_PID2="$!"
sleep 1

echo "log-for-console-2" > remote
sleep 1
grep -qF "log-for-console-2" "$TEST_LOG_OTHER"


