# Generated by configure script

PREFIX = /usr
SYSCONFDIR = /etc
LOCALSTATEDIR = /var
SYSTEMD_SYSTEM_UNIT_DIR = /lib/systemd/system
UDEV_RULES_DIR = 

ENABLE_SSH = no
ENABLE_UDEV = no
ENABLE_CONCURRENT_SERVERS = no
ENABLE_TESTS = no

CC = gcc
